on: push

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: sudo apt-get update
    - run: sudo apt-get install clang-10 binaryen
    - uses: neomura/setup-aseprite-cli-action@v1.0.0
    - run: make
