on: [push]

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update
    - run: sudo apt-get install clang-10 binaryen
    - uses: neomura/setup-aseprite-cli-action@v1.0.0
    - run: make
